name: CI Pipeline

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: 3.12
    - uses: iterative/setup-cml@v2

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install - r requirements.txt
        
    - name: Run main file
      run: |
        python main.py

    - name: Run tests
      run: |
        python -m unittest discover

    - name: Create cml report
      env:
        REPO_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        echo "# First line of our report" >> report.md
        echo "## Bar Plots" >> report.md
        echo '![](./bars.png "Bar plot")' >> report.md
        echo "## Line Plots" >> report.md
        echo '![](./lines.png "Bar plot")' >> report.md

        cml comment create report.md